### ISSUE TITLE
Supporting gcc-aarch64-linux 9.x

### ISSUE THREAD

**Issue by rageworx** [rageworx/rk3399_linux_kernel_4.4.179#4]
There's many big issues while compile with gcc-aarch64 9.4 on Mint Linux 20.x
Most of range error/warnings.
Is it should be avoid by using -Wno-* ?
Not sure.

**Comment by rageworx** [comment]
Should be refer to https://github.com/rockchip-linux/kernel/issues/160

**Comment by adjexpress** [comment]
i also have this problem while using buildroot gcc 8, 9 or 10 with uclibc .
any solution for this ?

**Comment by rageworx** [comment]
> i also have this problem while using buildroot gcc 8, 9 or 10 with uclibc . any solution for this ?

Not yet, tried a couple of times, but it seems gcc-9 need new kernel version like 5.x.
Rockchip linux kernel seems to only availed for gcc-linaro-6.3.1.

**Comment by rageworx** [comment]
> i also have this problem while using buildroot gcc 8, 9 or 10 with uclibc . any solution for this ?

Dear @adjexpress, It was solved to using arm gcc-8.3 for now.
Have you tried it ?
You can refer to my issue [here](https://github.com/rageworx/rock960linux/issues/5).

**Comment by rageworx** [comment]
Now compilation successfully availed for 
- gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu
- Ubuntu 22.04LTS (amd64), by using latest apt packages rather than using old deb-packages.

**Comment by rageworx** [comment]
Plus, also working debian-10(buster) for now.
